Repository ChampSim/ChampSim, pull requests merged in 2023-03, with the labels that each got.

#314 Created a configuration file for Dependabot
  .github/dependabot.yml
Labels: enhancement, dependencies

#312 Coveralls Integration
  .github/workflows/test.yml
  README.md
  test/cpp/src/800-vmem-period.cc
Labels: enhancement

#320 Only update btb with a valid target.
  btb/basic_btb/basic_btb.cc
  test/cpp/src/165-basic-btb-no-evict-on-unknown-target.cc
  test/cpp/src/166-issue296-basic-btb-no-mispredict-on-not-taken.cc
Labels: bug
